kind: Deployment
apiVersion: apps/v1
metadata:
   name: my-deployment
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: ubuntu-app
   template:
     metadata:
       name: ubuntu-pod
       labels:
         name: ubuntu-app
     spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo welcome-from-ubuntu; sleep 5; done"]