kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod  
  annotations:
    description: This is first K8S pod (annotations)                
  labels:
    env: stage
    cloud: aws
    app: ubuntu

spec:                                    
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo Hello Sanjay; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always