kind: Pod
apiVersion: v1
metadata:
  name: node-label
  labels:
    env: dev

spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo sanjay-kumar; sleep 5; done"]
  
  nodeSelector:
    hardware: t2.medium  

