apiVersion: v1
kind: ReplicationController
metadata:
   name: my-rc
   labels:
     application: my-app
     tier: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels:
        application: my-app
        tier: front-end
    spec:
      containers:
        - name: app-pod
          image: nginx
  replicas: 2
