kind: ReplicaSet              #This defines to create the Replication Controller object             
apiVersion: apps/v1
metadata:
  name: my-rs
spec:
  replicas: 2                 # desired number of pods
  selector:                   # The selector tells the controller which pods to watch/belong to this RS
    matchExpressions:         # the below conditions must match the labels
      - {key: name, operator: In, values: [ubuntu-app, Ubuntu-App, UBUNTU-APP]}
      - {key: env, operator: NotIn, values: [prod]}
  template:                   # Template element defines a template to launch a new pod
    metadata:                 
      name: pod-ubuntu        # name of the pod
      labels:                 # selector value needs to match the labels values specified in the pod template
        name: ubuntu-app
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Sanjay; sleep 5 ; done"]