#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# please use the below command for creating the secret files 
# $ echo "root" > username.txt; echo "mypassword123" > password.txt
# 
# echo "<configuration text " > sample.conf
# kubectl create secret generic mysecret --from-file=username.txt --from-file=password.txt
# 
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
apiVersion: v1
kind: Pod
metadata:
  name: myvolsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Technical-guftgu; sleep 5 ; done"]
    volumeMounts:
      - name: testsecret
        mountPath: "/tmp/mysecrets"   # the secret files will be mounted as ReadOnly by default here
  volumes:
  - name: testsecret
    secret:
       secretName: mysecret  