apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-app
    env: dev
    tier: front-end
  name: nginx-pod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
    env: dev
    tier: front-end
  type: nodeport
status:
  loadBalancer: {}
